[package]
name = "aurora"
version = "0.1.0"
authors = ["SeptFox <1751634419@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
